import type { Transaction } from "@/modules/dashboard/types/Transaction";

export const mockTransactions: Transaction[] = [
  {
    id: "1",
    date: "2024-02-13",
    type: "expense",
    category: "Продукти",
    categoryIcon: "🛒",
    description: "Сільпо",
    amount: 850.5,
    card: "Monobank",
  },
  {
    id: "2",
    date: "2024-02-13",
    type: "income",
    category: "Зарплата",
    categoryIcon: "💰",
    description: "Місячна зарплата",
    amount: 25000,
    card: "ПриватБанк",
  },
  {
    id: "3",
    date: "2024-02-12",
    type: "expense",
    category: "Транспорт",
    categoryIcon: "🚗",
    description: "Bolt поїздка",
    amount: 180,
    card: "Monobank",
  },
  {
    id: "4",
    date: "2024-02-12",
    type: "expense",
    category: "Ресторани",
    categoryIcon: "🍽️",
    description: "Обід з колегами",
    amount: 450,
    card: "Cashback",
  },
  {
    id: "5",
    date: "2024-02-11",
    type: "expense",
    category: "Підписки",
    categoryIcon: "📱",
    description: "Netflix Premium",
    amount: 350,
    card: "Monobank",
  },
  {
    id: "6",
    date: "2024-02-11",
    type: "income",
    category: "Фріланс",
    categoryIcon: "💻",
    description: "Розробка сайту",
    amount: 5000,
    card: "ПриватБанк",
  },
  {
    id: "7",
    date: "2024-02-10",
    type: "expense",
    category: "Здоров'я",
    categoryIcon: "💊",
    description: "Аптека 9-1-1",
    amount: 320,
    card: "Monobank",
  },
  {
    id: "8",
    date: "2024-02-10",
    type: "expense",
    category: "Розваги",
    categoryIcon: "🎬",
    description: "Кінотеатр Multiplex",
    amount: 400,
    card: "Cashback",
  },
  {
    id: "9",
    date: "2024-02-10",
    type: "expense",
    category: "Розваги",
    categoryIcon: "🎬",
    description: "Кінотеатр Multiplex",
    amount: 400,
    card: "Cashback",
  },
  {
    id: "10",
    date: "2024-02-10",
    type: "expense",
    category: "Розваги",
    categoryIcon: "й🎬",
    description: "Кінотеатр Multiplex",
    amount: 400,
    card: "Cashback",
  },
  {
    id: "11",
    date: "2024-02-10",
    type: "expense",
    category: "Розвіііііаги",
    categoryIcon: "🎬",
    description: "Кінотеатр Multiplex",
    amount: 400,
    card: "Cashback",
  },
  {
    id: "12",
    date: "2024-02-10",
    type: "expense",
    category: "Розйцуваги",
    categoryIcon: "🎬",
    description: "Кінотеатр Multiplex",
    amount: 400,
    card: "Cashback",
  },
];
